[package]
name = "gremlin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gremlin"

[dependencies]
num = "0.4.0"

[[bin]]
name = "gremlin"
test = false
doc = false